# dont forget to first download slave.jar
# wget http://localhost:9090/jenkins/jnlpJars/slave.jar
#

FROM jamesdbloom/docker-java8-maven
# create files if you want to share workspace etc.
#RUN  mkdir /home/jenkins
#RUN  mkdir /home/jenkins/agent
#RUN ip address && wget http://localhost:9090/jenkins/jnlpJars/slave.jar -P /home/jenkins/
#COPY ./slave.jar /home/jenkins
# ip address needs to be run for refresh 
#CMD ["sh","-c","update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java && ip address && http://localhost:9090/jenkins/jnlpJars/slave.jar -P /home/jenkins/ && java -jar /home/jenkins/slave.jar -jnlpUrl http://localhost:9090/jenkins/computer/agent1/slave-agent.jnlp"]
CMD ["sh","-c","update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java && ip address && wget http://localhost:9090/jenkins/jnlpJars/slave.jar -P /home/jenkins/ && java -jar /home/jenkins/slave.jar -jnlpUrl http://localhost:9090/jenkins/computer/agent1/slave-agent.jnlp"]

# now run this 
# docker build -t "j:s" . && docker run --net="host" j:s
